version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: dockerfilepostgres
    container_name: crimewatch_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn CrimeWatch.wsgi:application --bind 0.0.0.0:8000"
    container_name: CrimeWatch
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
