# Use an official Python runtime as a parent image
FROM python:3.9-slim

#RUN apt-get update && apt-get install -y nodejs npm

RUN apt-get update && apt-get install -y binutils libproj-dev gdal-bin

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /crimeapp

COPY requirements.txt .
#COPY GDAL-3.8.4-cp312-cp312-win_amd64.whl .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn

# Copy project
COPY . .
ENV DB_HOST=db
ENV POSTGRES_PASSWORD=2525

#COPY Frontend/package-lock.json /crimeapp/Frontend/
#WORKDIR /crimeapp/Frontend
#RUN npm install
#RUN npm run build

#RUN mv dist/* ../static/

# Move back to the main app directory
#WORKDIR /crimeapp

# Collect static files
RUN python manage.py collectstatic --noinput

# Expose the port the app runs on
EXPOSE 8000

# Run the application
#CMD ["gunicorn", "--bind", ":8000", "--workers", "3", "--timeout", "120", "CrimeWatch.wsgi:application"]
