# Generated by Django 5.0.4 on 2024-05-12 20:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('primaryid', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('location_type', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('street', models.CharField(blank=True, max_length=100)),
                ('context', models.TextField(blank=True)),
                ('outcome_status', models.CharField(blank=True, max_length=200, null=True)),
                ('persistent_id', models.CharField(blank=True, max_length=100)),
                ('report_id', models.BigIntegerField(blank=True, null=True)),
                ('location_subtype', models.CharField(blank=True, max_length=100)),
                ('month', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Backend.coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCrimeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('crime_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='Backend.coordinates')),
            ],
            options={
                'unique_together': {('month', 'location')},
            },
        ),
    ]
